version: '3.8'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./workflows:/data/workflows
      - ./scripts:/data/scripts
    depends_on:
      - redis
    networks:
      - automate-net

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - automate-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - n8n
    networks:
      - automate-net

networks:
  automate-net:
    driver: bridge